// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: transaction_dlq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionDLQ represents a dead letter queue message for failed transactions
type TransactionDLQ struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OriginalKey      string                 `protobuf:"bytes,1,opt,name=original_key,json=originalKey,proto3" json:"original_key,omitempty"`
	OriginalValue    []byte                 `protobuf:"bytes,2,opt,name=original_value,json=originalValue,proto3" json:"original_value,omitempty"`
	Error            string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	OriginalSchemaId int32                  `protobuf:"varint,4,opt,name=original_schema_id,json=originalSchemaId,proto3" json:"original_schema_id,omitempty"` // Optional, use 0 for not set
	FailedAt         string                 `protobuf:"bytes,5,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	RetryCount       int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"` // Optional, use 0 for not set
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionDLQ) Reset() {
	*x = TransactionDLQ{}
	mi := &file_transaction_dlq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDLQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDLQ) ProtoMessage() {}

func (x *TransactionDLQ) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_dlq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDLQ.ProtoReflect.Descriptor instead.
func (*TransactionDLQ) Descriptor() ([]byte, []int) {
	return file_transaction_dlq_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionDLQ) GetOriginalKey() string {
	if x != nil {
		return x.OriginalKey
	}
	return ""
}

func (x *TransactionDLQ) GetOriginalValue() []byte {
	if x != nil {
		return x.OriginalValue
	}
	return nil
}

func (x *TransactionDLQ) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TransactionDLQ) GetOriginalSchemaId() int32 {
	if x != nil {
		return x.OriginalSchemaId
	}
	return 0
}

func (x *TransactionDLQ) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *TransactionDLQ) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_transaction_dlq_proto protoreflect.FileDescriptor

const file_transaction_dlq_proto_rawDesc = "" +
	"\n" +
	"\x15transaction_dlq.proto\x12\blocal_db\"\xdc\x01\n" +
	"\x0eTransactionDLQ\x12!\n" +
	"\foriginal_key\x18\x01 \x01(\tR\voriginalKey\x12%\n" +
	"\x0eoriginal_value\x18\x02 \x01(\fR\roriginalValue\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12,\n" +
	"\x12original_schema_id\x18\x04 \x01(\x05R\x10originalSchemaId\x12\x1b\n" +
	"\tfailed_at\x18\x05 \x01(\tR\bfailedAt\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCountB\x10Z\x0elocal_db/protob\x06proto3"

var (
	file_transaction_dlq_proto_rawDescOnce sync.Once
	file_transaction_dlq_proto_rawDescData []byte
)

func file_transaction_dlq_proto_rawDescGZIP() []byte {
	file_transaction_dlq_proto_rawDescOnce.Do(func() {
		file_transaction_dlq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_dlq_proto_rawDesc), len(file_transaction_dlq_proto_rawDesc)))
	})
	return file_transaction_dlq_proto_rawDescData
}

var file_transaction_dlq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_dlq_proto_goTypes = []any{
	(*TransactionDLQ)(nil), // 0: local_db.TransactionDLQ
}
var file_transaction_dlq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_dlq_proto_init() }
func file_transaction_dlq_proto_init() {
	if File_transaction_dlq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_dlq_proto_rawDesc), len(file_transaction_dlq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_dlq_proto_goTypes,
		DependencyIndexes: file_transaction_dlq_proto_depIdxs,
		MessageInfos:      file_transaction_dlq_proto_msgTypes,
	}.Build()
	File_transaction_dlq_proto = out.File
	file_transaction_dlq_proto_goTypes = nil
	file_transaction_dlq_proto_depIdxs = nil
}
